"""Initial schema: 7 tables for Telegram chatbot with persistent memory

Revision ID: 1f61cecb9b98
Revises: 
Create Date: 2025-11-19 16:20:18.620982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f61cecb9b98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('telegram_user_id > 0', name='chk_telegram_user_id_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_last_interaction', 'users', ['last_interaction_at'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_users_last_interaction_at'), 'users', ['last_interaction_at'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('analytics_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.Enum('BOT_STARTED', 'COMMAND_USED', 'CONVERSATION_STARTED', 'CONVERSATION_ENDED', 'CONTEXT_RETRIEVED', 'ERROR_OCCURRED', name='event_type_enum'), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_context', sa.Enum('DESAYUNOS', 'RESIS', 'COLES', 'DANA', 'KAYAK', 'GENERAL', 'UNKNOWN', name='project_context_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_active', 'conversations', ['user_id', 'is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_conversations_updated_at', 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_project_context'), 'conversations', ['project_context'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consent_type', sa.Enum('DATA_STORAGE', 'ANALYTICS', 'MARKETING', name='consent_type_enum'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(granted = TRUE AND granted_at IS NOT NULL) OR (granted = FALSE AND revoked_at IS NOT NULL)', name='chk_granted_logic'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consents_type', 'user_consents', ['consent_type', 'granted'], unique=False)
    op.create_index('idx_consents_unique', 'user_consents', ['user_id', 'consent_type'], unique=True)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('context_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_context', sa.Enum('DESAYUNOS', 'RESIS', 'COLES', 'DANA', 'KAYAK', 'GENERAL', 'UNKNOWN', name='project_context_enum'), nullable=False),
    sa.Column('detected_topics', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_user_query', sa.Text(), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('message_count >= 0', name='chk_message_count_positive'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_conversation_id', 'context_snapshots', ['conversation_id'], unique=False)
    op.create_index('idx_snapshots_created_at', 'context_snapshots', ['created_at'], unique=False)
    op.create_index('idx_snapshots_project', 'context_snapshots', ['project_context'], unique=False)
    op.create_index('idx_snapshots_user_id', 'context_snapshots', ['user_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role != 'ASSISTANT' OR confidence_score IS NOT NULL", name='chk_assistant_has_confidence'),
    sa.CheckConstraint('LENGTH(TRIM(content)) > 0', name='chk_content_not_empty'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0.0 AND confidence_score <= 1.0)', name='chk_confidence_range'),
    sa.CheckConstraint('telegram_message_id IS NULL OR telegram_message_id > 0', name='chk_telegram_message_id_positive'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_confidence', 'messages', ['confidence_score'], unique=False, postgresql_where=sa.text("role = 'ASSISTANT'"))
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False, postgresql_where=sa.text("role = 'USER'"))
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Enum('POSITIVE', 'NEGATIVE', name='feedback_rating_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('comment IS NULL OR LENGTH(comment) <= 500', name='chk_comment_length'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_message_id'), 'feedback', ['message_id'], unique=True)
    op.create_index(op.f('ix_feedback_rating'), 'feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_rating'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_message_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_messages_role', table_name='messages', postgresql_where=sa.text("role = 'USER'"))
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.drop_index('idx_messages_confidence', table_name='messages', postgresql_where=sa.text("role = 'ASSISTANT'"))
    op.drop_table('messages')
    op.drop_index('idx_snapshots_user_id', table_name='context_snapshots')
    op.drop_index('idx_snapshots_project', table_name='context_snapshots')
    op.drop_index('idx_snapshots_created_at', table_name='context_snapshots')
    op.drop_index('idx_snapshots_conversation_id', table_name='context_snapshots')
    op.drop_table('context_snapshots')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index('idx_consents_unique', table_name='user_consents')
    op.drop_index('idx_consents_type', table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_context'), table_name='conversations')
    op.drop_index('idx_conversations_updated_at', table_name='conversations')
    op.drop_index('idx_conversations_active', table_name='conversations', postgresql_where=sa.text('is_active = true'))
    op.drop_table('conversations')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_interaction_at'), table_name='users')
    op.drop_index('idx_users_last_interaction', table_name='users', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
